site_name: MaskMyPy Documentation
site_description: Geographic Masking Python Package
site_url: https://thetinhat.github.io/MaskMyPy/
theme:
    name: 'material'
    # logo: assets/logo.png
    # favicon: assets/favicon.ico
    site_url: https://thetinhat.github.io/MaskMyPy/
    palette:
      scheme: default
      primary: teal
      accent: teal


# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - git-revision-date-localized:
      timezone: America/Vancouver

extra_css:
  - assets/css/extra.css