site_name: MaskMyPy Documentation
site_description: Geographic Masking Python Package
site_url: https://thetinhat.github.io/MaskMyPy/
theme:
    name: 'material'
    site_url: https://thetinhat.github.io/MaskMyPy/
    logo: assets/python_logo.png

markdown_extensions:
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - roamlinks
  - mkdocstrings:
      handlers:
        python:
          selection:
            show_root_heading: false
            docstring_style: numpy
            show_source: false
            merge_init_into_class: true
            docstring_section_style: list
            heading_level: 3
            line_length: 99
          paths: [.]
  - git-revision-date-localized:
      timezone: America/Vancouver

extra_css:
  - assets/style.css