site_name: MaskMyPy Documentation
site_description: Geographic Masking Python Package
site_url: https://thetinhat.github.io/MaskMyPy/
theme:
    name: 'material'
    # logo: assets/logo.png
    # favicon: assets/favicon.ico
    site_url: https://thetinhat.github.io/MaskMyPy/

# Extensions
markdown_extensions:
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - git-revision-date-localized:
      timezone: America/Vancouver

extra_css:
  - stylesheets/extra.css