name: Build and Publish Docs
on:
  push:
    branches:
      - beta
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "maskmypy/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-roamlinks-plugin mkdocs-git-revision-date-localized-plugin mkdocstrings-python
      - run: mkdocs gh-deploy --force
