name: Test Package
on:
  push:
    branches: ['**']
    paths:
      - 'maskmypy/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'setup.py'
      - '.github/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .[extra]
      - name: Test package
        run: pytest
